<template>
  <main class="debug-page">
    <section class="hero">
      <p class="eyebrow">Realtime Lesson Console</p>
      <h1>Browser speech capture, transcript review, and scoped lesson QA</h1>
      <p class="hero-copy">
        Start a lesson session, stream microphone audio to the backend, review persisted transcript chunks, then ask
        questions against the current lesson or the course history.
      </p>
    </section>

    <section class="grid">
      <article class="panel controls">
        <h2>Session Controls</h2>

        <label class="field">
          <span>Backend HTTP URL</span>
          <input v-model.trim="backendHttpUrl" type="text" placeholder="http://127.0.0.1:8000" />
        </label>

        <label class="field">
          <span>Subject</span>
          <input v-model.trim="subject" type="text" placeholder="Calculus review" />
        </label>

        <label class="field">
          <span>Course ID</span>
          <input v-model.trim="courseId" type="text" placeholder="Leave blank to let the backend derive one" />
        </label>

        <label class="field">
          <span>Client ID</span>
          <input v-model.trim="clientId" type="text" placeholder="browser-debug" />
        </label>

        <label class="field">
          <span>Model</span>
          <select v-model="modelName" class="select">
            <option v-for="model in modelOptions" :key="model.value" :value="model.value">
              {{ model.label }}
            </option>
          </select>
        </label>

        <label class="field">
          <span>Microphone</span>
          <select v-model="selectedInputDeviceId" class="select">
            <option value="">System default microphone</option>
            <option v-for="device in inputDevices" :key="device.deviceId" :value="device.deviceId">
              {{ device.label || `microphone-${device.deviceId.slice(0, 6)}` }}
            </option>
          </select>
        </label>

        <div class="actions">
          <button class="button" @click="loadInputDevices" :disabled="loadingDevices">
            {{ loadingDevices ? 'Loading devices...' : 'Refresh microphones' }}
          </button>
          <button class="button primary" @click="createSession" :disabled="creatingSession">
            {{ creatingSession ? 'Creating...' : 'Create session' }}
          </button>
          <button class="button" @click="connectSocket" :disabled="connectingSocket || !sessionId || isSocketOpen">
            {{ connectingSocket ? 'Connecting...' : 'Connect WebSocket' }}
          </button>
          <button class="button" @click="disconnectSocket" :disabled="!websocket">
            Disconnect
          </button>
        </div>

        <div class="actions">
          <button class="button accent" @click="startRecording" :disabled="!isSocketOpen || isRecording">
            Start recording
          </button>
          <button class="button danger" @click="stopRecording" :disabled="!isRecording">
            Stop recording
          </button>
          <button class="button" @click="resetView">
            Clear panels
          </button>
        </div>

        <dl class="status-list">
          <div>
            <dt>Session ID</dt>
            <dd>{{ sessionId || 'Not created yet' }}</dd>
          </div>
          <div>
            <dt>Course ID</dt>
            <dd>{{ courseId || 'Pending backend value' }}</dd>
          </div>
          <div>
            <dt>Lesson ID</dt>
            <dd>{{ lessonId || 'Auto-generated by backend' }}</dd>
          </div>
          <div>
            <dt>WebSocket</dt>
            <dd>{{ socketStatus }}</dd>
          </div>
          <div>
            <dt>Model</dt>
            <dd>{{ currentModelName || modelName || 'default' }}</dd>
          </div>
          <div>
            <dt>Recording</dt>
            <dd>{{ isRecording ? 'recording' : 'stopped' }}</dd>
          </div>
          <div>
            <dt>Detected inputs</dt>
            <dd>{{ inputDevices.length }}</dd>
          </div>
          <div>
            <dt>WS URL</dt>
            <dd class="mono">{{ backendWsUrl }}</dd>
          </div>
        </dl>

        <p v-if="errorMessage" class="error">{{ errorMessage }}</p>
      </article>

      <article class="panel transcript">
        <h2>Realtime Transcript</h2>
        <div class="transcript-block">
          <span class="label">Partial</span>
          <p>{{ partialText || 'Waiting for incremental transcript output...' }}</p>
        </div>

        <div class="transcript-block">
          <span class="label">Final</span>
          <ul v-if="finalTexts.length" class="final-list">
            <li v-for="item in finalTexts" :key="item.seq">
              <span class="seq">#{{ item.seq }}</span>
              <span>{{ item.text }}</span>
            </li>
          </ul>
          <p v-else>No final transcript segments yet.</p>
        </div>
      </article>

      <article class="panel query-panel">
        <div class="panel-head">
          <h2>Lesson QA</h2>
          <button class="button ghost" @click="clearQueryResult" :disabled="!queryAnswer && !queryResults.length">
            Clear
          </button>
        </div>

        <label class="field">
          <span>Question</span>
          <textarea
            v-model.trim="queryInput"
            rows="4"
            placeholder="Ask about the current lesson or the course history..."
          />
        </label>

        <label class="field">
          <span>Scope</span>
          <select v-model="queryScope" class="select">
            <option v-for="option in queryScopeOptions" :key="option.value" :value="option.value">
              {{ option.label }}
            </option>
          </select>
        </label>

        <label class="checkbox-row">
          <input v-model="queryWithLlm" type="checkbox" />
          <span>Use LLM answer synthesis when backend LLM mode is enabled</span>
        </label>

        <div class="actions">
          <button class="button primary" @click="submitQuery" :disabled="loadingQuery || !queryInput.trim()">
            {{ loadingQuery ? 'Querying...' : 'Ask question' }}
          </button>
          <button class="button" @click="useLatestFinalAsQuestion" :disabled="!finalTexts.length">
            Use latest final transcript
          </button>
        </div>

        <div v-if="queryMetadata.scope || queryMetadata.course_id || queryMetadata.lesson_id" class="metadata-grid">
          <div>
            <dt>Effective scope</dt>
            <dd>{{ formatScope(queryMetadata.scope) }}</dd>
          </div>
          <div>
            <dt>Course</dt>
            <dd>{{ stringValue(queryMetadata.course_id) }}</dd>
          </div>
          <div>
            <dt>Lesson</dt>
            <dd>{{ stringValue(queryMetadata.lesson_id) }}</dd>
          </div>
        </div>

        <div class="transcript-block">
          <span class="label">Answer</span>
          <p v-if="queryAnswer">{{ queryAnswer }}</p>
          <p v-else-if="queryResults.length">
            Retrieval-only mode returned source chunks without synthesized answer text.
          </p>
          <p v-else>No query has been run yet.</p>
        </div>

        <div class="transcript-block">
          <span class="label">Retrieved Chunks</span>
          <ul v-if="queryResults.length" class="result-list">
            <li v-for="item in queryResults" :key="item.doc_id" class="result-card">
              <div class="result-meta">
                <span class="event-type">{{ item.doc_id }}</span>
                <span v-if="typeof item.score === 'number'" class="mono">score={{ item.score.toFixed(3) }}</span>
              </div>
              <div class="badge-row">
                <span v-if="item.subject" class="badge">{{ item.subject }}</span>
                <span v-if="item.metadata?.course_id" class="badge">course={{ stringValue(item.metadata.course_id) }}</span>
                <span v-if="item.metadata?.lesson_id" class="badge">lesson={{ stringValue(item.metadata.lesson_id) }}</span>
              </div>
              <p>{{ item.content }}</p>
            </li>
          </ul>
          <p v-else>No retrieval results yet.</p>
        </div>
      </article>

      <article class="panel metrics">
        <h2>Audio Metrics</h2>
        <dl class="status-list">
          <div>
            <dt>RMS</dt>
            <dd>{{ audioMetrics.rms ?? '-' }}</dd>
          </div>
          <div>
            <dt>Peak</dt>
            <dd>{{ audioMetrics.peak ?? '-' }}</dd>
          </div>
          <div>
            <dt>Event count</dt>
            <dd>{{ events.length }}</dd>
          </div>
        </dl>
      </article>

      <article class="panel transcript">
        <div class="panel-head">
          <h2>Persisted Transcript</h2>
          <button class="button ghost" @click="fetchPersistedTranscripts" :disabled="loadingPersisted || !sessionId">
            {{ loadingPersisted ? 'Loading...' : 'Refresh' }}
          </button>
        </div>
        <ul v-if="persistedTranscripts.length" class="final-list">
          <li v-for="item in persistedTranscripts" :key="item.chunk_id">
            <span class="seq">#{{ item.chunk_id }}</span>
            <span>{{ item.clean_text || item.text }}</span>
          </li>
        </ul>
        <p v-else>{{ sessionId ? 'No persisted transcript chunks yet.' : 'Create a session first.' }}</p>
      </article>

      <article class="panel events">
        <div class="panel-head">
          <h2>Event Stream</h2>
          <button class="button ghost" @click="events = []">Clear</button>
        </div>
        <ul class="event-list">
          <li v-for="item in events" :key="item.id">
            <div class="event-meta">
              <span class="event-type">{{ item.type }}</span>
              <span class="mono">seq={{ item.seq ?? '-' }}</span>
              <span>{{ item.time }}</span>
            </div>
            <pre>{{ item.payload }}</pre>
          </li>
        </ul>
      </article>
    </section>
  </main>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'

type BackendEvent = {
  type: string
  session_id?: string
  course_id?: string
  lesson_id?: string
  model_name?: string
  seq?: number
  text?: string
  rms?: number
  peak?: number
  [key: string]: unknown
}

type EventLogItem = {
  id: string
  type: string
  seq?: number
  time: string
  payload: string
}

type InputDeviceOption = {
  deviceId: string
  label: string
}

type PersistedTranscriptItem = {
  chunk_id: number
  text: string
  clean_text: string
  course_id?: string | null
  lesson_id?: string | null
}

type ModelOption = {
  value: string
  label: string
}

type QueryScope = 'auto' | 'current_lesson' | 'course_history' | 'course_all' | 'global'

type QueryResultItem = {
  doc_id: string
  content: string
  score?: number | null
  session_id?: string | null
  subject?: string | null
  source_type?: string | null
  metadata: Record<string, unknown>
}

type QueryResponse = {
  query: string
  answer?: string | null
  results?: QueryResultItem[]
  metadata?: Record<string, unknown>
}

type SessionResponse = {
  session_id: string
  course_id?: string | null
  lesson_id?: string | null
  model_name?: string | null
}

const modelOptions: ModelOption[] = [
  { value: 'paraformer-zh', label: 'paraformer-zh' },
  { value: 'paraformer-zh-streaming', label: 'paraformer-zh-streaming' },
]

const queryScopeOptions: Array<{ value: QueryScope; label: string }> = [
  { value: 'auto', label: 'Auto' },
  { value: 'current_lesson', label: 'Current lesson' },
  { value: 'course_history', label: 'Course history' },
  { value: 'course_all', label: 'Whole course' },
  { value: 'global', label: 'Global knowledge base' },
]

const scopeLabels: Record<QueryScope, string> = {
  auto: 'Auto',
  current_lesson: 'Current lesson',
  course_history: 'Course history',
  course_all: 'Whole course',
  global: 'Global knowledge base',
}

const backendHttpUrl = ref('http://127.0.0.1:8000')
const subject = ref('Speech debug')
const courseId = ref('')
const lessonId = ref('')
const clientId = ref('browser-debug')
const modelName = ref('paraformer-zh')

const sessionId = ref('')
const currentModelName = ref('')
const socketStatus = ref('idle')
const partialText = ref('')
const finalTexts = ref<Array<{ seq: number; text: string }>>([])
const events = ref<EventLogItem[]>([])
const errorMessage = ref('')
const creatingSession = ref(false)
const connectingSocket = ref(false)
const isRecording = ref(false)
const loadingDevices = ref(false)
const loadingQuery = ref(false)
const audioMetrics = ref<{ rms?: string; peak?: string }>({})
const inputDevices = ref<InputDeviceOption[]>([])
const selectedInputDeviceId = ref('')
const persistedTranscripts = ref<PersistedTranscriptItem[]>([])
const loadingPersisted = ref(false)
const queryInput = ref('')
const queryScope = ref<QueryScope>('auto')
const queryWithLlm = ref(false)
const queryAnswer = ref('')
const queryResults = ref<QueryResultItem[]>([])
const queryMetadata = ref<Record<string, unknown>>({})

let websocket: WebSocket | null = null
let mediaStream: MediaStream | null = null
let audioContext: AudioContext | null = null
let sourceNode: MediaStreamAudioSourceNode | null = null
let processorNode: ScriptProcessorNode | null = null

const isSocketOpen = computed(() => socketStatus.value === 'open')

const backendWsUrl = computed(() => {
  try {
    const url = new URL(backendHttpUrl.value)
    url.protocol = url.protocol === 'https:' ? 'wss:' : 'ws:'
    url.pathname = sessionId.value ? `/ws/audio/${sessionId.value}` : '/ws/audio/{session_id}'
    url.search = ''
    url.hash = ''
    return url.toString()
  } catch {
    return 'ws://invalid-url/ws/audio/{session_id}'
  }
})

function pushEvent(event: BackendEvent | Record<string, unknown>) {
  const normalized = event as BackendEvent
  events.value.unshift({
    id: `${Date.now()}-${Math.random().toString(16).slice(2)}`,
    type: normalized.type ?? 'unknown',
    seq: normalized.seq,
    time: new Date().toLocaleTimeString(),
    payload: JSON.stringify(event, null, 2),
  })
}

function stringValue(value: unknown) {
  if (value === null || value === undefined) {
    return '-'
  }
  const text = String(value).trim()
  return text || '-'
}

function formatScope(value: unknown) {
  if (typeof value !== 'string') {
    return '-'
  }
  return scopeLabels[value as QueryScope] ?? value
}

function applySessionContext(
  payload: {
    course_id?: string | null
    lesson_id?: string | null
    model_name?: string | null
  },
) {
  if (typeof payload.course_id === 'string') {
    courseId.value = payload.course_id
  }
  if (typeof payload.lesson_id === 'string') {
    lessonId.value = payload.lesson_id
  }
  if (typeof payload.model_name === 'string') {
    currentModelName.value = payload.model_name
  }
}

async function loadInputDevices() {
  errorMessage.value = ''
  loadingDevices.value = true

  try {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
    stream.getTracks().forEach((track) => track.stop())

    const devices = await navigator.mediaDevices.enumerateDevices()
    inputDevices.value = devices
      .filter((device) => device.kind === 'audioinput')
      .map((device) => ({
        deviceId: device.deviceId,
        label: device.label,
      }))

    if (
      selectedInputDeviceId.value &&
      !inputDevices.value.some((device) => device.deviceId === selectedInputDeviceId.value)
    ) {
      selectedInputDeviceId.value = ''
    }

    pushEvent({
      type: 'input_devices_loaded',
      count: inputDevices.value.length,
      selected_device_id: selectedInputDeviceId.value || null,
    })
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : 'load input devices failed'
  } finally {
    loadingDevices.value = false
  }
}

async function createSession() {
  errorMessage.value = ''
  creatingSession.value = true
  try {
    const response = await fetch(`${backendHttpUrl.value}/sessions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        subject: subject.value || null,
        course_id: courseId.value || null,
        client_id: clientId.value || null,
        sample_rate: 16000,
        channels: 1,
        model_name: modelName.value || null,
      }),
    })

    if (!response.ok) {
      throw new Error(`create session failed: ${response.status}`)
    }

    const data = (await response.json()) as SessionResponse
    sessionId.value = data.session_id
    currentModelName.value = data.model_name ?? ''
    applySessionContext(data)
    persistedTranscripts.value = []
    clearQueryResult()
    pushEvent({ type: 'session_created', ...data })
    await fetchPersistedTranscripts()
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : 'create session failed'
  } finally {
    creatingSession.value = false
  }
}

async function fetchPersistedTranscripts() {
  if (!sessionId.value) {
    persistedTranscripts.value = []
    return
  }

  loadingPersisted.value = true
  try {
    const response = await fetch(`${backendHttpUrl.value}/sessions/${sessionId.value}/transcripts`)
    if (!response.ok) {
      throw new Error(`fetch transcripts failed: ${response.status}`)
    }

    const data = (await response.json()) as { items?: PersistedTranscriptItem[] }
    persistedTranscripts.value = Array.isArray(data.items) ? data.items.slice().reverse() : []
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : 'fetch transcripts failed'
  } finally {
    loadingPersisted.value = false
  }
}

async function submitQuery() {
  errorMessage.value = ''

  if (!queryInput.value.trim()) {
    errorMessage.value = 'query text is required'
    return
  }

  if (!sessionId.value) {
    await createSession()
  }

  if (!sessionId.value) {
    return
  }

  loadingQuery.value = true
  try {
    const response = await fetch(`${backendHttpUrl.value}/sessions/${sessionId.value}/query`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        query: queryInput.value.trim(),
        scope: queryScope.value,
        with_llm: queryWithLlm.value,
      }),
    })

    if (!response.ok) {
      throw new Error(`query failed: ${response.status}`)
    }

    const data = (await response.json()) as QueryResponse
    queryAnswer.value = data.answer ?? ''
    queryResults.value = Array.isArray(data.results) ? data.results : []
    queryMetadata.value = data.metadata ?? {}
    applySessionContext({
      course_id: typeof data.metadata?.course_id === 'string' ? data.metadata.course_id : undefined,
      lesson_id: typeof data.metadata?.lesson_id === 'string' ? data.metadata.lesson_id : undefined,
    })
    pushEvent({
      type: 'rag_query_completed',
      query: data.query,
      result_count: queryResults.value.length,
      scope: data.metadata?.scope ?? queryScope.value,
      with_llm: queryWithLlm.value,
    })
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : 'query failed'
  } finally {
    loadingQuery.value = false
  }
}

function clearQueryResult() {
  queryAnswer.value = ''
  queryResults.value = []
  queryMetadata.value = {}
}

function useLatestFinalAsQuestion() {
  const latest = finalTexts.value[0]
  if (!latest) {
    return
  }
  queryInput.value = latest.text
}

async function connectSocket() {
  errorMessage.value = ''
  if (!sessionId.value) {
    await createSession()
  }
  if (!sessionId.value || websocket) {
    return
  }

  connectingSocket.value = true
  socketStatus.value = 'connecting'

  try {
    websocket = new WebSocket(backendWsUrl.value)

    websocket.onopen = () => {
      socketStatus.value = 'open'
      connectingSocket.value = false
      pushEvent({ type: 'socket_open', session_id: sessionId.value })
    }

    websocket.onmessage = (event) => {
      const payload = JSON.parse(event.data) as BackendEvent
      pushEvent(payload)

      if (payload.type === 'session_started') {
        applySessionContext(payload)
      }

      if (payload.type === 'partial_transcript') {
        partialText.value = payload.text ?? ''
      }

      if (payload.type === 'final_transcript' && payload.text) {
        finalTexts.value.unshift({
          seq: payload.seq ?? finalTexts.value.length + 1,
          text: payload.text,
        })
        partialText.value = ''
        void fetchPersistedTranscripts()
      }

      if (payload.type === 'audio_metrics') {
        audioMetrics.value = {
          rms: typeof payload.rms === 'number' ? payload.rms.toFixed(4) : '-',
          peak: typeof payload.peak === 'number' ? payload.peak.toFixed(4) : '-',
        }
      }
    }

    websocket.onerror = () => {
      errorMessage.value = 'websocket error'
      socketStatus.value = 'error'
    }

    websocket.onclose = () => {
      socketStatus.value = 'closed'
      websocket = null
      connectingSocket.value = false
      stopRecording()
      pushEvent({ type: 'socket_closed', session_id: sessionId.value })
    }
  } catch (error) {
    connectingSocket.value = false
    socketStatus.value = 'error'
    websocket = null
    errorMessage.value = error instanceof Error ? error.message : 'connect websocket failed'
  }
}

function disconnectSocket() {
  stopRecording()
  websocket?.close()
  websocket = null
  socketStatus.value = 'closed'
}

function resetView() {
  partialText.value = ''
  finalTexts.value = []
  persistedTranscripts.value = []
  events.value = []
  errorMessage.value = ''
  audioMetrics.value = {}
  clearQueryResult()
}

function downsampleBuffer(buffer: Float32Array, inputRate: number, outputRate: number) {
  if (outputRate === inputRate) {
    return buffer
  }

  const ratio = inputRate / outputRate
  const outputLength = Math.round(buffer.length / ratio)
  const result = new Float32Array(outputLength)

  let offsetResult = 0
  let offsetBuffer = 0

  while (offsetResult < result.length) {
    const nextOffsetBuffer = Math.round((offsetResult + 1) * ratio)
    let accum = 0
    let count = 0

    for (let index = offsetBuffer; index < nextOffsetBuffer && index < buffer.length; index += 1) {
      accum += buffer[index] ?? 0
      count += 1
    }

    result[offsetResult] = count > 0 ? accum / count : 0
    offsetResult += 1
    offsetBuffer = nextOffsetBuffer
  }

  return result
}

async function startRecording() {
  errorMessage.value = ''

  if (!isSocketOpen.value) {
    errorMessage.value = 'websocket is not connected'
    return
  }

  if (isRecording.value) {
    return
  }

  try {
    if (!inputDevices.value.length) {
      await loadInputDevices()
    }

    mediaStream = await navigator.mediaDevices.getUserMedia({
      audio: {
        deviceId: selectedInputDeviceId.value ? { exact: selectedInputDeviceId.value } : undefined,
        channelCount: 1,
        echoCancellation: false,
        noiseSuppression: false,
        autoGainControl: false,
      },
    })

    audioContext = new AudioContext()
    sourceNode = audioContext.createMediaStreamSource(mediaStream)
    processorNode = audioContext.createScriptProcessor(4096, 1, 1)

    processorNode.onaudioprocess = (event) => {
      if (!websocket || websocket.readyState !== WebSocket.OPEN) {
        return
      }
      const channelData = event.inputBuffer.getChannelData(0)
      const copied = new Float32Array(channelData)
      const downsampled = downsampleBuffer(copied, audioContext?.sampleRate ?? 48000, 16000)
      websocket.send(downsampled.buffer)
    }

    sourceNode.connect(processorNode)
    processorNode.connect(audioContext.destination)
    isRecording.value = true
    pushEvent({
      type: 'recording_started',
      selected_device_id: selectedInputDeviceId.value || null,
    })
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : 'start recording failed'
    stopRecording()
  }
}

function stopRecording() {
  if (processorNode) {
    processorNode.disconnect()
    processorNode.onaudioprocess = null
    processorNode = null
  }
  if (sourceNode) {
    sourceNode.disconnect()
    sourceNode = null
  }
  if (mediaStream) {
    mediaStream.getTracks().forEach((track) => track.stop())
    mediaStream = null
  }
  if (audioContext) {
    void audioContext.close()
    audioContext = null
  }
  if (isRecording.value) {
    pushEvent({ type: 'recording_stopped' })
  }
  isRecording.value = false
}

onBeforeUnmount(() => {
  stopRecording()
  disconnectSocket()
})
</script>
